<?php

declare(strict_types=1);

/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace VerizonLib\Models;

use stdClass;

class GetDeviceExperienceScoreBulkRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $accountName;

    /**
     * @var DeviceIdentifier[]
     */
    private $deviceListItem;

    /**
     * @param string $accountName
     * @param DeviceIdentifier[] $deviceListItem
     */
    public function __construct(string $accountName, array $deviceListItem)
    {
        $this->accountName = $accountName;
        $this->deviceListItem = $deviceListItem;
    }

    /**
     * Returns Account Name.
     */
    public function getAccountName(): string
    {
        return $this->accountName;
    }

    /**
     * Sets Account Name.
     *
     * @required
     * @maps accountName
     */
    public function setAccountName(string $accountName): void
    {
        $this->accountName = $accountName;
    }

    /**
     * Returns Device List Item.
     *
     * @return DeviceIdentifier[]
     */
    public function getDeviceListItem(): array
    {
        return $this->deviceListItem;
    }

    /**
     * Sets Device List Item.
     *
     * @required
     * @maps deviceListItem
     *
     * @param DeviceIdentifier[] $deviceListItem
     */
    public function setDeviceListItem(array $deviceListItem): void
    {
        $this->deviceListItem = $deviceListItem;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['accountName']    = $this->accountName;
        $json['deviceListItem'] = $this->deviceListItem;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
